{
 "title": "CKB Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  { "title": "System/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process (RSS)",
   "type": "graph",
   "description": "Resident set size of CKB process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_process{type=\"rss\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process (VMS)",
   "type": "graph",
   "description": "Virtual memory of CKB process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_process{type=\"vms\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jemalloc",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ckb_sys_mem_jemalloc", "legendFormat": "{{instance}}/{{type}}" }
   ]
  },
  {
   "title": "RocksDB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ckb_sys_mem_rocksdb) by (instance, type)",
     "legendFormat": "{{instance}}/{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB (Current Memtables)",
   "type": "graph",
   "description": "[rocksdb.cur-size-all-mem-tables] Approximate size of active and unflushed immutable memtables (bytes).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_rocksdb{type=\"cur-size-all-mem-tables\"}",
     "legendFormat": "{{instance}}/{{cf}}"
    }
   ]
  },
  {
   "title": "RocksDB (Memtables)",
   "type": "graph",
   "description": "[rocksdb.size-all-mem-tables] Approximate size of active, unflushed immutable, and pinned immutable memtables (bytes).",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_rocksdb{type=\"size-all-mem-tables\"}",
     "legendFormat": "{{instance}}/{{cf}}"
    }
   ]
  },
  {
   "title": "RocksDB (Block Cache Usage)",
   "type": "graph",
   "description": "[rocksdb.block-cache-usage] The memory size for the entries residing in block cache.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_rocksdb{type=\"block-cache-usage\"}",
     "legendFormat": "{{instance}}/{{cf}}"
    }
   ]
  },
  {
   "title": "RocksDB (Block Cache Capacity)",
   "type": "graph",
   "description": "[rocksdb.block-cache-capacity] Block cache capacity.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_sys_mem_rocksdb{type=\"block-cache-capacity\"}",
     "legendFormat": "{{instance}}/{{cf}}"
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Tip Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "ckb_chain_tip_number", "legendFormat": "{{instance}}/{{type}}" }
   ]
  },
  {
   "title": "Insert Block Elapsed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(ckb_chain_insert_block{type=\"elapsed\", quantile=\"0.9\"}, \"block_type\", \"uncle\", \"is_uncle\", \"true\"), \"block_type\", \"main\", \"is_uncle\", \"false\")",
     "legendFormat": "{{instance}}/{{block_type}}/p90"
    }
   ]
  },
  {
   "title": "Reorg Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "ckb_chain_reorg", "legendFormat": "{{instance}}/{{type}}" }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Message Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_net_received[1m])",
     "legendFormat": "{{instance}}/{{action}}/{{item}}"
    }
   ]
  },
  {
   "title": "Message Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_net_sent[1m])",
     "legendFormat": "{{instance}}/{{action}}/{{item}}"
    }
   ]
  },
  {
   "title": "Message Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_net_status[1m])",
     "legendFormat": "{{instance}}/{{action}}/{{status}}"
    }
   ]
  },
  {
   "title": "Compact Block Fresh",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ckb_net_fresh",
     "legendFormat": "{{instance}}/{{type}}/{{status}}"
    }
   ]
  },
  {
   "title": "Blocks In Flight (Elapsed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ckb_net_blocks_in_flight{type=\"elapsed_ms\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/p90"
    }
   ]
  },
  {
   "title": "Blocks In Flight (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ckb_net_blocks_in_flight{type=\"total\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/p90"
    }
   ]
  },
  {
   "title": "Get Ancestor (Elapsed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_net_get_ancestor{type=\"elapsed\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/p90"
    }
   ]
  },
  {
   "title": "Get Ancestor (Steps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ckb_net_get_ancestor{type=\"steps\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/p90"
    }
   ]
  },
  {
   "title": "Get Ancestor (Numbers)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ckb_net_get_ancestor{type=\"base_number\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/{{type}}/p90"
    },
    {
     "expr": "ckb_net_get_ancestor{type=\"target_number\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/{{type}}/p90"
    },
    {
     "expr": "ckb_net_get_ancestor{type=\"ancestor_number\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}/{{type}}/p90"
    }
   ]
  }
 ]
}