{
 "title": "CKB",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "MainTip",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_chain_main_chain_tip{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-MainTip"
    }
   ]
  },
  {
   "title": "MainTipInc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_gauge_chain_main_chain_tip{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-MainTipInc"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_sent_GetBlockProposal{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-GetBlockProposal"
    },
    {
     "expr": "rate(ckb_counter_sent_GetBlockTransactions{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}--GetBlockTransactions"
    },
    {
     "expr": "rate(ckb_counter_sent_GetBlocks{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-GetBlocks"
    },
    {
     "expr": "rate(ckb_counter_sent_GetRelayTransactions{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}--GetRelayTransactions"
    },
    {
     "expr": "rate(ckb_counter_sent_SendHeaders{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-SendHeaders"
    }
   ]
  },
  {
   "title": "Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_received_BlockProposal{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-BlockProposal"
    },
    {
     "expr": "rate(ckb_counter_received_BlockTransactions{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-BlockTransactions"
    },
    {
     "expr": "rate(ckb_counter_received_CompactBlock{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-CompactBlock"
    },
    {
     "expr": "rate(ckb_counter_received_GetHeaders{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-GetHeaders"
    },
    {
     "expr": "rate(ckb_counter_received_RelayTransactionHashes{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-RelayTransactionHashes"
    },
    {
     "expr": "rate(ckb_counter_received_RelayTransactions{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-RelayTransactions"
    },
    {
     "expr": "rate(ckb_counter_received_SendBlock{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-SendBlock"
    },
    {
     "expr": "rate(ckb_counter_received_SendHeaders{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-SendHeaders"
    }
   ]
  },
  {
   "title": "BlocksInFlight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_blocks_in_flight_total{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-BlocksInFlight"
    }
   ]
  },
  {
   "title": "BlockInFlightElapsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_blocks_in_flight_elapsed{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-BlocksInFlightElapsed"
    }
   ]
  },
  {
   "title": "GetAncestorSteps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_get_ancestor_steps{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-GetAncestorSteps"
    }
   ]
  },
  {
   "title": "GetAncestorElapsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_get_ancestor_elapsed{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-GetAncestorElapsed"
    }
   ]
  },
  {
   "title": "Reorg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_reorg_attached{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-Attached"
    },
    {
     "expr": "rate(ckb_counter_reorg_detached{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-Detached"
    }
   ]
  },
  {
   "title": "MainTipCost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_chain_elapsed{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-chain-cost"
    }
   ]
  },
  {
   "title": "HeaderTip",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_chain_header_chain_tip{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-HeaderTip"
    }
   ]
  },
  {
   "title": "FetchBlocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_block_fetcher_elapsed_div_nfetch{job=\"ckb\",instance=~\"$node\"}[15m])",
     "legendFormat": "{{instance}}-elapsed_div_nfetch"
    }
   ]
  },
  {
   "title": "FetchBlocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_gauge_fetch_blocks_elapsed{job=\"ckb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}-elapsed"
    },
    {
     "expr": "rate(ckb_counter_fetch_blocks_duplicated{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-duplicated-counter"
    },
    {
     "expr": "rate(ckb_counter_fetch_blocks_received{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-received-counter"
    },
    {
     "expr": "rate(ckb_counter_fetch_blocks_stored{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-stored-counter"
    },
    {
     "expr": "rate(ckb_counter_fetch_blocks_steps{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-steps-counter"
    }
   ]
  },
  {
   "title": "ProcessBlock",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_counter_process_block_received{job=\"ckb\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-received"
    }
   ]
  }
 ]
}