{
 "title": "Peers",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,5m,10m,30m" },
   {
    "name": "total_peers",
    "label": "TotalPeers",
    "query": "query_result(ckb_peers_total{job=\"$job\", env=\"$env\", instance=~\"$instance\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Local",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ckb_shared_best_header_number{job=\"$job\",env=\"$env\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Peers (Total $total_peers)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ckb_peer_attr", "legendFormat": "222" },
    {
     "expr": "ckb_peer_last_common_header_number"
    },
    {
     "expr": "ckb_peer_best_known_header_number"
    },
    { "expr": "ckb_peer_tasks_limit" },
    { "expr": "ckb_peer_n_tx_ask_for" }
   ]
  },
  {
   "title": "Peers Assigned Tasks in Recent $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_peer_accumulated_tasks_total{job=\"$job\",env=\"$env\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "peer-{{host}}"
    }
   ]
  }
 ]
}