{
 "title": "Epoch",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "network", "query": "ckb,ckb_testnet" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH timed_epoch AS (\n    SELECT time_bucket(INTERVAL '$interval', start_time) AS bucket,\n           length\n    FROM $network.epoch\n    WHERE $__timeFilter(start_time)\n)\n\nSELECT e.bucket AS time,\n       avg(e.length) AS \"Mean\"\nFROM timed_epoch as e\nGROUP BY e.bucket\nORDER BY e.bucket;\n"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH timed_epoch AS (\n    SELECT time_bucket(INTERVAL '$interval', start_time) AS bucket,\n           (end_time - start_time) AS \"duration\"\n    FROM $network.epoch\n    WHERE $__timeFilter(start_time)\n)\n\nSELECT e.bucket AS time,\n       avg(EXTRACT(EPOCH FROM e.duration)) AS \"Mean\"\nFROM timed_epoch as e\nGROUP BY e.bucket\nORDER BY e.bucket;\n\n"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "rawSql": "WITH timed_epoch AS (\n    SELECT time_bucket(INTERVAL '$interval', start_time) AS bucket,\n           difficulty\n    FROM $network.epoch\n    WHERE $__timeFilter(start_time)\n)\n\nSELECT e.bucket AS time,\n       avg(e.difficulty) AS \"Mean\"\nFROM timed_epoch as e\nGROUP BY e.bucket\nORDER BY e.bucket;\n"
    }
   ]
  },
  {
   "title": "HashRate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "rawSql": "WITH timed_epoch AS (\n    SELECT time_bucket(INTERVAL '$interval', start_time) AS bucket,\n           difficulty,\n           (end_time - start_time) AS duration\n    FROM $network.epoch\n    WHERE $__timeFilter(start_time)\n)\n\nSELECT  e.bucket AS time,\n        avg(e.difficulty / EXTRACT(EPOCH FROM e.duration)) AS \"Mean\"\nFROM timed_epoch as e\nGROUP BY e.bucket\nORDER BY e.bucket;\n"
    }
   ]
  }
 ]
}