{
 "title": "Peer",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "network", "query": "ckb,ckb_testnet" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH time_filtered_peer_record AS (\n    SELECT *\n    FROM $network.peer\n    -- WHERE time BETWEEN '2021-12-16T09:04:29.452Z' AND '2021-12-16T10:04:29.453Z'\n    WHERE $__timeFilter(time)\n),\nsorted_peer_record AS (\n    SELECT peer.*,\n           ROW_NUMBER() OVER (PARTITION BY ip ORDER BY time DESC) AS rn\n    FROM time_filtered_peer_record AS peer\n),\nlast_peer_record AS (\n    SELECT * FROM sorted_peer_record WHERE rn = 1\n)\nSELECT now() AS time, version AS measurement, COUNT(DISTINCT ipinfo.ip) AS \" \"\nFROM last_peer_record peer INNER JOIN $network.ipinfo ipinfo USING (ip)\nGROUP BY version;\n"
    }
   ]
  },
  {
   "title": "Country Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH time_filtered_peer_record AS (\n    SELECT *\n    FROM $network.peer\n    -- WHERE time BETWEEN '2021-12-16T09:04:29.452Z' AND '2021-12-16T10:04:29.453Z'\n    WHERE $__timeFilter(time)\n),\nsorted_peer_record AS (\n    SELECT peer.*,\n           ROW_NUMBER() OVER (PARTITION BY ip ORDER BY time DESC) AS rn\n    FROM time_filtered_peer_record AS peer\n),\nlast_peer_record AS (\n    SELECT * FROM sorted_peer_record WHERE rn = 1\n)\nSELECT now() AS time, ipinfo.country AS measurement, COUNT(DISTINCT ipinfo.ip) AS \" \"\nFROM last_peer_record peer INNER JOIN $network.ipinfo ipinfo USING (ip)\nGROUP BY ipinfo.country;\n"
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH timed_peer AS (\n    SELECT\n        ip,\n        version,\n        time_bucket(INTERVAL '$interval', time) AS bucket\n    FROM $network.peer\n    -- WHERE time BETWEEN '2021-12-16T09:04:29.452Z' AND '2021-12-16T10:04:29.453Z'\n    WHERE $__timeFilter(time)\n),\ncounted_peer AS (\n    SELECT\n        COUNT(DISTINCT ip) AS value,\n        bucket,\n        version\n    FROM timed_peer\n    GROUP BY bucket, version\n)\nSELECT\n    bucket AS time,\n    version AS metric,\n    value\nFROM counted_peer;\n"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH peer_ip AS (\n    SELECT DISTINCT ON (bucket, ip) time_bucket(INTERVAL '$interval', time) as bucket,\n                                             ip\n    FROM $network.peer\n)\nSELECT p.bucket as time,\n       count(*)  AS \"Nodes\"\nFROM peer_ip as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Reachable (How many public nodes this peer can reach)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH timed_peer AS (\n    SELECT\n        time AS \"time\",\n        ip,\n        version,\n        n_reachable\n    FROM ckb.peer\n    -- FROM $network.peer\n    WHERE\n        time BETWEEN '2021-12-17T09:27:28.289Z' AND '2021-12-18T09:27:28.289Z'\n        -- $__timeFilter(time)\n),\nsorted_peer AS (\n    SELECT\n        timed_peer.*,\n        ROW_NUMBER() OVER (PARTITION BY ip ORDER BY n_reachable) AS rn\n    FROM timed_peer\n),\nmax_peer AS (\n    SELECT *\n    FROM sorted_peer\n    WHERE rn = 1\n),\ncountry_peer AS (\n    SELECT peer.*, ipinfo.country  FROM max_peer peer INNER JOIN $network.ipinfo ipinfo USING (ip)\n)\nSELECT \n    ip,\n    version,\n    country,\n    n_reachable AS reachable\nFROM country_peer\nORDER BY time;\n"
    }
   ]
  }
 ]
}