{
 "title": "FreshTransactions",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Fresh Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_fresh_transactions_total{job=\"$job\",env=\"$env\",instance=~\"$instance\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Fresh Uncles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_fresh_uncles_total{job=\"$job\",env=\"$env\",instance=~\"$instance\"} OR on() vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fresh Proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ckb_fresh_proposals_total{job=\"$job\",env=\"$env\",instance=~\"$instance\"} OR on() vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}