{
 "title": "Network",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Connection Events in Recent $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(ckb_connections_total{env=\"$env\", job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  { "title": "Out Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_messages_total{job=\"$job\",direction=\"out\"}[$interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_messages_bytes{job=\"$job\",direction=\"out\"}[$interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  { "title": "In Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_messages_total{job=\"$job\",direction=\"in\"}[$interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ckb_messages_bytes{job=\"$job\",direction=\"in\"}[$interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  { "title": "Blocks In-Flight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_blocks_in_flight_total{job=\"ckb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ckb_block_in_flight_ms{job=\"ckb\",quantile=\"0.5\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    },
    {
     "expr": "ckb_block_in_flight_ms{job=\"ckb\",quantile=\"0.95\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  }
 ]
}