{
 "title": "Pool",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Pending Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_size{job=\"$job\",name=\"pending\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_bytes{job=\"ckb\",name=\"pending\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_cycles{job=\"ckb\",name=\"pending\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Proposed Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_size{job=\"ckb\",name=\"proposed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_bytes{job=\"ckb\",name=\"proposed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_cycles{job=\"ckb\",name=\"proposed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Gap Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_size{job=\"ckb\",name=\"gap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_bytes{job=\"ckb\",name=\"gap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_cycles{job=\"ckb\",name=\"gap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Orphan Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_pool_size{job=\"ckb\",name=\"orphan\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}