{
 "title": "Synchronization",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Get Blocks To Fetch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_get_blocks_to_fetch{job=\"ckb\",quantile=\"0.9\"} OR on() vector(0)",
     "legendFormat": "{{instance}}-{{quantile}}"
    },
    {
     "expr": "ckb_get_blocks_to_fetch{job=\"ckb\",quantile=\"0.99\"} OR on() vector(0)",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Sum Cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_get_blocks_to_fetch_sum{job=\"$job\"} OR on() vector(0)",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_get_blocks_to_fetch_count{job=\"ckb\"} OR on() vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}