{
 "title": "Verifier",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "ckb" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=\"$job\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$job\",env=\"$env\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Verified Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Contextual Verified Transaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_contextual_verified_tx{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  { "title": "Verified Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Contextual Verified Block",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_contextual_verified_block{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "NonContextual Verified Block",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_noncontextual_verified_block{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Contextual Verified BlockTransactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_contextual_verified_block_txs{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "NonContextual Verified BlockTransactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_noncontextual_verified_block_txs{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  { "title": "Verified Script", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Verified Script",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ckb_verified_script{job=\"ckb\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Verified Script Cycles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ckb_verified_script_cycles{job=\"ckb\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  }
 ]
}