{
 "title": "Alerting",
 "description": "A List of Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* Alert Title Suffix with `(network = $network)`\n\n   Being aware of which network is alerting\n   is important for maintainers. As Grafana\n   alerting messages are not supported to \n   contain template variables, we have to\n   attach the network name onto the alert\n   title. The message tag is another way\n   to distinguish the networks but it does\n   not display in the email subject.\n\n\n* Target Message Channel\n\n  There are two message channels, \n  wangguozhen@cryptape.com, and the another \n  is to the whole ckb team.\n\n  - \"No Data Alert\" alerts only send to \n  wangguozhen@cryptape.com; \n  - Alerts for wano network only send to \n  wangguozhen@cryptape.com; \n  - The rest send to the whole ckb team."
   }
  },
  { "title": "aggron alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Tip Change (network = aggron)",
   "type": "graph",
   "description": "Tip number change indicates the change growth.\n\nWhen the tip number doesn't change for a long time,\nthe chain may suspend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'aggron') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  {
   "title": "Block Time Interval (network = aggron)",
   "type": "graph",
   "description": "Block time interval relates to the network mining power and the network propagation. A continuous long block time interval is a warning.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = aggron)",
   "type": "graph",
   "description": "There is a transaction being pending for a long time.\n\nTransactions should be packaged within new blocks or removed because of invalidation. Therefore if there are any pending-too-long transactions, tx-pool may have trouble.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = aggron)",
   "type": "graph",
   "description": "There is a transaction being proposed for a long time.\n\nTransactions should be packaged within new blocks or removed because of invalidation. Therefore if there are any proposed-too-long transactions, tx-pool may have trouble.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  {
   "title": "No Data Alert (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "block",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  { "title": "lina alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Tip Change (network = lina)",
   "type": "graph",
   "description": "Tip number change indicates the change growth.\n\nWhen the tip number doesn't change for a long time,\nthe chain may suspend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'lina') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  {
   "title": "Block Time Interval (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  {
   "title": "No Data Alert (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "block",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  { "title": "wano alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Tip Change (network = wano)",
   "type": "graph",
   "description": "Tip number change indicates the change growth.\n\nWhen the tip number doesn't change for a long time,\nthe chain may suspend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'wano') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  },
  {
   "title": "Block Time Interval (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  },
  {
   "title": "No Data Alert (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "block",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  }
 ]
}