{
 "title": "Canonical Chain",
 "description": "The Canonical Chain History",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "SHOW TAG VALUES  WITH KEY = \"network\" "
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* This dashboard's data source is the canonical chain.\n\n\n* To omit the block race problem, we let the\nmonitoring canonical lags behind the real-time\nblockchain for a while(10 blocks).\n\n\n* As epoch adjustment occurs nearly every 4 hours,\nit would be best if you extended the time zone to see the epoch history."
   }
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "number",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Time Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "distinct block time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Transactions / Proposals Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "block transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "block proposals",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "proposals_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Per Second (in 5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Commit Transactions per Second (interval=5m)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "block",
     "query": "SELECT \"transactions_count\" FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / (5 * 60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Propose Transactions per Second (interval=5m)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "blocks",
     "query": "SELECT \"transactions_count\" FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "proposals_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / (5 * 60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Commit Transactions per Second (interval=1m)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "block",
     "query": "SELECT \"transactions_count\" FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / (1 * 60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Propose Transactions per Second (interval=1m)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "blocks",
     "query": "SELECT \"transactions_count\" FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "proposals_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / (1 * 60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Epochs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Epochs",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "measurement": "epochs",
     "query": "SELECT \"number\", \"length\", \"duration\"  / 1000 / 60 / 60, \"uncles_count\" FROM \"epoch\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000 / 60 / 60" ], "type": "math" }
      ],
      [
       { "params": [ "uncles_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Epochs Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"length\" FROM \"epoch\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Epochs Block Time (Duration / Length)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"duration\" / \"length\" FROM \"epoch\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Epochs Uncle Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "uncle rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"uncles_count\" / \"length\" FROM \"epoch\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Epochs Uncle Rate Derivative",
   "type": "graph",
   "description": "The Thresholds are defined based on mainnet",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "derivative(12h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(\"uncles_count\" / \"length\", 12h) FROM \"epoch\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Uncles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Recent 15 Uncles",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "limit": "15",
     "measurement": "uncle",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "2PC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "2PC Delay != 2 Traffic (WIP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count of transactions (2pc delay != 2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction",
     "query": "SELECT count(\"pc_delay\") FROM \"transaction\" WHERE (\"network\" =~ /^$network$/ AND \"pc_delay\" > 2) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pc_delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "2PC Delay (WIP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count of transactions (2pc delay != 2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction",
     "query": "SELECT count(\"pc_delay\") FROM \"transaction\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pc_delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "count of transactions (2pc delay == 2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction",
     "query": "SELECT count(\"pc_delay\") FROM \"transaction\" WHERE (\"network\" =~ /^$network$/ AND \"pc_delay\" = 2) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pc_delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "2PC Delay Distribution (WIP)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "2pc delay",
     "measurement": "transaction",
     "select": [
      [
       { "params": [ "pc_delay" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  }
 ]
}