{
 "title": "Chain",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "SHOW TAG VALUES  WITH KEY = \"network\" "
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "number",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Time Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean 1h block time",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Transactions / Proposals Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "block transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    },
    {
     "alias": "block proposals",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "proposals_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "measurement": "epochs",
     "query": "SELECT \"number\", \"length\", \"duration\"  / 1000 / 60 / 60, \"uncles_count\" FROM \"epochs\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000 / 60 / 60" ], "type": "math" }
      ],
      [
       { "params": [ "uncles_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Epochs Uncle Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"uncles_count\" / \"length\" FROM \"epochs\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Epochs Uncle Rate Derivative",
   "type": "graph",
   "description": "The Thresholds are defined based on mainnet",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "derivative(12h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(\"uncles_count\" / \"length\", 12h) FROM \"epochs\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Uncles",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "measurement": "uncles",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  }
 ]
}