{
 "title": "Network Propagation",
 "description": "A Network Prober",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "SHOW TAG VALUES  WITH KEY = \"network\" "
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" WHERE network = '$network'"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* The data source is a external network prober.\n\n  The external network prober connect to all public\npeers, and record the network propagation\nfrom its view.\n\n\n* Most of time the \"High Latency Table\" and\n\"High Latency Logs\" is no-data state. It is OK."
   }
  },
  {
   "title": "Total Public Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total public peers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "peers",
     "select": [
      [
       { "params": [ "peers_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Compact Block Propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "propagation-99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "propagation",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "message_type", "operator": "=", "value": "compact_block" },
      { "condition": "AND", "key": "percentile", "operator": "=", "value": "99" }
     ]
    },
    {
     "alias": "propagation-80th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "propagation",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "message_type", "operator": "=", "value": "compact_block" },
      { "condition": "AND", "key": "percentile", "operator": "=", "value": "80" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "propagation-99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "propagation",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "message_type", "operator": "=", "value": "transaction_hash" },
      { "condition": "AND", "key": "percentile", "operator": "=", "value": "99" }
     ]
    },
    {
     "alias": "propagation-80th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "propagation",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "message_type", "operator": "=", "value": "transaction_hash" },
      { "condition": "AND", "key": "percentile", "operator": "=", "value": "80" }
     ]
    }
   ]
  },
  {
   "title": "High Latency Of Block Propagation Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "addr" ], "type": "tag" }
     ],
     "measurement": "high_latency",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "High Latency Of Block Propagation Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "addr" ], "type": "tag" }
     ],
     "measurement": "high_latency",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}