# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus-ckb
    # <string, required> datasource type. Required
    type: prometheus
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    # defined service in docker-compose.yaml
    url: prometheus:9090
    # <string> database user, if used
    editable: true
    jsonData:
      manageAlerts: true
