{
 "title": "Alerting",
 "description": "A List of Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "aggron alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Canonical Tip Change (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'aggron') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  {
   "title": "Canonical Block Time Interval (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = aggron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "aggron" }
     ]
    }
   ]
  },
  { "title": "lina alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Canonical Tip Change (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'lina') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  {
   "title": "Canonical Block Time Interval (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = lina)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "lina" }
     ]
    }
   ]
  },
  { "title": "wano alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Canonical Tip Change (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "tip number change in 10m",
     "measurement": "block",
     "query": "SELECT non_negative_derivative(\"number\", 5m) FROM \"block\" WHERE (\"network\" = 'wano') AND $timeFilter",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "10m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  },
  {
   "title": "Canonical Block Time Interval (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "block time interval in 10m",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "network" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "time_interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Pending Too Long (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "pending_long" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Being Proposed Too Long (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "proposed long transactions",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx-transition",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "propose_long" }
     ]
    }
   ]
  },
  {
   "title": "Error/Warning Logs (network = wano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "error/warning logs count",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "log",
     "select": [
      [
       { "params": [ "marker" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=", "value": "wano" }
     ]
    }
   ]
  }
 ]
}