{
 "title": "Block",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "network", "query": "ckb,ckb_testnet" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Mean Transactions ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH block_mean_transactions AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_transactions\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       avg(p.n_transactions)  AS \"Mean Transactions\"\nFROM block_mean_transactions as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Sum Transactions ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH block_sum_transactions AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_transactions\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       sum(p.n_transactions)  AS \"Sum Transactions\"\nFROM block_sum_transactions as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Mean Proposals ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH block_mean_proposals AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_proposals\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       avg(p.n_proposals)  AS \"Mean Proposals\"\nFROM block_mean_proposals as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Sum Proposals ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH block_sum_proposals AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_proposals\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       sum(p.n_proposals)  AS \"Sum Proposals\"\nFROM block_sum_proposals as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Sum Uncles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH block_mean_uncles AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_uncles\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       avg(p.n_uncles)  AS \"Mean uncles\"\nFROM block_mean_uncles as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;\n"
    }
   ]
  },
  {
   "title": "Sum Uncles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH block_sum_uncles AS (\n    SELECT time_bucket(INTERVAL '$interval', time) as bucket,\n           n_uncles\n    FROM $network.block\n)\nSELECT p.bucket as time,\n       sum(p.n_uncles)  AS \"Sum uncles\"\nFROM block_sum_uncles as p\nWHERE $__timeFilter(p.bucket)\nGROUP BY p.bucket\nORDER BY p.bucket;"
    }
   ]
  }
 ]
}