{
 "title": "Pool",
 "time": { "from": "2021-10-29T07:06:06.601Z", "to": "2021-10-29T16:52:20.387Z" },
 "templating": {
  "list": [
   { "name": "network", "label": "network", "query": "ckb,ckb_testnet" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pending as \"Pending\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  proposed as \"Proposed\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  orphan as \"Orphan\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket(INTERVAL '$interval', time) AS \"time\",\n  avg(pending) as \"Mean Pending ($interval)\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket(INTERVAL '$interval', time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket(INTERVAL '$interval', time) AS \"time\",\n  avg(proposed) as \"Mean Proposed ($interval)\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket(INTERVAL '$interval', time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket(INTERVAL '$interval', time) AS \"time\",\n  avg(orphan) as \"Mean Orphan ($interval)\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket(INTERVAL '$interval', time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pool Stat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_tx_size as \"Total Transaction Size\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_tx_cycles as \"Total Transaction Cycles\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Abnormal Logs (It's Okay that no data)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_tx_size AS \"TotalTxSize\",\n  total_tx_cycles AS \"TotalTxCycles\",\n  proposed AS \"Proposed\",\n  pending AS \"Pending\",\n  orphan AS \"Orphan\"\nFROM $network.tx_pool_info\nWHERE\n  $__timeFilter(time) AND proposed = 0 AND pending = 0 AND orphan = 0 AND (total_tx_size != 0 OR total_tx_cycles != 0)\nORDER BY 1"
    }
   ]
  }
 ]
}